Name:           ros-hydro-fanuc
Version:        0.3.1
Release:        0%{?dist}
Summary:        ROS fanuc package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/fanuc
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-hydro-fanuc-assets
Requires:       ros-hydro-fanuc-driver
Requires:       ros-hydro-fanuc-lrmate200ic-moveit-config
Requires:       ros-hydro-fanuc-lrmate200ic-moveit-plugins
Requires:       ros-hydro-fanuc-lrmate200ic-support
Requires:       ros-hydro-fanuc-lrmate200ic5h-moveit-config
Requires:       ros-hydro-fanuc-lrmate200ic5l-moveit-config
Requires:       ros-hydro-fanuc-m10ia-moveit-config
Requires:       ros-hydro-fanuc-m10ia-moveit-plugins
Requires:       ros-hydro-fanuc-m10ia-support
Requires:       ros-hydro-fanuc-m16ib-moveit-plugins
Requires:       ros-hydro-fanuc-m16ib-support
Requires:       ros-hydro-fanuc-m16ib20-moveit-config
Requires:       ros-hydro-fanuc-m20ia-moveit-config
Requires:       ros-hydro-fanuc-m20ia-moveit-plugins
Requires:       ros-hydro-fanuc-m20ia-support
Requires:       ros-hydro-fanuc-m20ia10l-moveit-config
Requires:       ros-hydro-fanuc-m430ia-moveit-plugins
Requires:       ros-hydro-fanuc-m430ia-support
Requires:       ros-hydro-fanuc-m430ia2f-moveit-config
Requires:       ros-hydro-fanuc-m430ia2p-moveit-config
Requires:       ros-hydro-fanuc-resources
BuildRequires:  ros-hydro-catkin

%description
ROS-Industrial support for Fanuc manipulators (metapackage).

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Wed Jan 21 2015 G.A. vd. Hoorn (TU Delft Robotics Institute) <g.a.vanderhoorn@tudelft.nl> - 0.3.1-0
- Autogenerated by Bloom

* Thu Jan 08 2015 G.A. vd. Hoorn (TU Delft Robotics Institute) <g.a.vanderhoorn@tudelft.nl> - 0.3.0-0
- Autogenerated by Bloom

