joint_limits:
  joint_5:
    has_velocity_limits: true
    max_velocity: 6.981317
    has_acceleration_limits: true
    max_acceleration: 1.3962634
  joint_2:
    has_velocity_limits: true
    max_velocity: 3.054326
    has_acceleration_limits: true
    max_acceleration: 0.6108652
  joint_6:
    has_velocity_limits: true
    max_velocity: 10.47198
    has_acceleration_limits: true
    max_acceleration: 2.094396
  joint_4:
    has_velocity_limits: true
    max_velocity: 6.981317
    has_acceleration_limits: true
    max_acceleration: 1.3962634
  joint_3:
    has_velocity_limits: true
    max_velocity: 3.141593
    has_acceleration_limits: true
    max_acceleration: 0.6283186
  joint_1:
    has_velocity_limits: true
    max_velocity: 3.403392
    has_acceleration_limits: true
    max_acceleration: 0.6806784