joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 5.24
    has_acceleration_limits: true
    max_acceleration: 1.048
  joint_4:
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: true
    max_acceleration: 1.256
  joint_2:
    has_velocity_limits: true
    max_velocity: 5.59
    has_acceleration_limits: true
    max_acceleration: 1.118
  joint_3:
    has_velocity_limits: true
    max_velocity: 5.59
    has_acceleration_limits: true
    max_acceleration: 1.118
  joint_5:
    has_velocity_limits: true
    max_velocity: 20.94
    has_acceleration_limits: true
    max_acceleration: 4.188