joint_limits:
  joint_4:
    has_velocity_limits: true
    max_velocity: 6.98
    has_acceleration_limits: true
    max_acceleration: 1.396
  joint_3:
    has_velocity_limits: true
    max_velocity: 3.67
    has_acceleration_limits: true
    max_acceleration: 0.734
  joint_1:
    has_velocity_limits: true
    max_velocity: 3.67
    has_acceleration_limits: true
    max_acceleration: 0.734
  joint_5:
    has_velocity_limits: true
    max_velocity: 6.98
    has_acceleration_limits: true
    max_acceleration: 1.396
  joint_2:
    has_velocity_limits: true
    max_velocity: 3.32
    has_acceleration_limits: true
    max_acceleration: 0.664
  joint_6:
    has_velocity_limits: true
    max_velocity: 10.47
    has_acceleration_limits: true
    max_acceleration: 2.094