joint_limits:
  joint_3:
    has_velocity_limits: true
    max_velocity: 3.0543
    has_acceleration_limits: true
    max_acceleration: 0.61086
  joint_1:
    has_velocity_limits: true
    max_velocity: 2.8798
    has_acceleration_limits: true
    max_acceleration: 0.57596
  joint_4:
    has_velocity_limits: true
    max_velocity: 6.1087
    has_acceleration_limits: true
    max_acceleration: 1.22174
  joint_5:
    has_velocity_limits: true
    max_velocity: 5.9341
    has_acceleration_limits: true
    max_acceleration: 1.18682
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.8798
    has_acceleration_limits: true
    max_acceleration: 0.57596
  joint_6:
    has_velocity_limits: true
    max_velocity: 9.0757
    has_acceleration_limits: true
    max_acceleration: 1.81514